### PR TITLE
fix(merge): incorrect caret position on merge

### LINKED ISSUE #73: Hydrate function messes caret when merging paragraphs
The Hydrate function from commit 103d75b causes a bug when merging blocks. Say that you have Paragraph_1 and Paragraph_2 (different blocks). When you press back on the beginning of Paragraph_2, the new state should be

Paragraph_1 [caret] Paragraph_2

But with the hydrate function the state we get is:

[caret] Paragraph_1 Paragraph_2

### PR DESCRIPTION
**Pull request by neSpecc**
# Problem

Right now caret restored at incorrect position after merging:

header merge is ok, paragraph is not:

https://github.com/editor-js/paragraph/assets/3684889/0f0ae9cd-2da9-450a-82d1-24e6398f9ba5

Can be reproduced in Safari. 

# Cause

In editor.js blockEvents we have this logic:

https://github.com/codex-team/editor.js/blob/b355f1673c11ec3c0603303aefaa6a546cf3a377/src/components/modules/blockEvents.ts#L488-L503

```ts
  private mergeBlocks(targetBlock: Block, blockToMerge: Block): void {
    const { BlockManager, Caret, Toolbar } = this.Editor;

    Caret.createShadow(targetBlock.pluginsContent);

    BlockManager
      .mergeBlocks(targetBlock, blockToMerge)
      .then(() => {
        window.requestAnimationFrame(() => {
          /** Restore caret position after merge */
          Caret.restoreCaret(targetBlock.pluginsContent as HTMLElement);
          targetBlock.pluginsContent.normalize();
          Toolbar.close();
        });
      });
  }
```

There is 2 problems:

- redundant `requestAnimationFrame`. It used only because paragraph `this.data` setter  updates DOM in `requestAnimationFrame`
- In `paragraph`'s `merge()` method we update DOM using `innerHTML` replacement. Link to the `shadow-caret` losing at that time

# Solution

- Get rid of `this.data` setter and getter. They has no sense and it's hard to maintain them: logic should be different in every case: 
  - `onPaste()` should use `RAF`, 
  - `render()` should not use RAF (#75), 
  - `merge()` should not break links to existing nodes, just append new content.
- `merge()` now just appends new content and don't breaks links to existing nodes (eg. shadow caret) 

Resolves #73

### CODE REVIEW

**Review by TatianaFomina — DISMISSED** [review]

File: src/utils/makeFragment.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+ *
+ * @param {string} htmlString - A string of valid HTML
+ * @returns {DocumentFragment}
+ */
+export default function makeFragment(htmlString) {
+  const tempDiv = document.createElement('div');
+
+  tempDiv.innerHTML = htmlString.trim();
+
+  var fragment = document.createDocumentFragment();
```
Comment (gohabereg) [inline src/utils/makeFragment.js:12]: var?

File: src/utils/makeFragment.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+  while (tempDiv.firstChild) {
+    fragment.appendChild(tempDiv.firstChild);
+  }
```
Comment (gohabereg) [inline src/utils/makeFragment.js:16]: Why not just `fragment.append(...Array.from(tempDiv.childNodes))`?

File: src/utils/makeFragment.js [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+ * @returns {DocumentFragment}
+ */
+export default function makeFragment(htmlString) {
+  const tempDiv = document.createElement('div');
+
+  tempDiv.innerHTML = htmlString.trim();
+
+  const fragment = document.createDocumentFragment();
+
+  fragment.appendChild(...Array.from(tempDiv.childNodes));
```
Comment (gohabereg) [inline src/utils/makeFragment.js:14]: appendChild accepts just one node
```suggestion
  fragment.append(...Array.from(tempDiv.childNodes));
```

**Review by gohabereg — CHANGES_REQUESTED** [review]

**Review by gohabereg — APPROVED** [review]

**Review by TatianaFomina — APPROVED** [review]
